version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

  frontend:
    build: ../client/k8s-kicks-frontend/
    ports:
      - "8080:80"

  merchant_register:
    build: ../merchant_register_microservice/src/
    ports:
      - "3001:3001"
    depends_on:
      - postgres