version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://myuser:mypass@postgres:5432/test_db

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  frontend:
    build: ../client/k8s-kicks-frontend/
    ports:
      - "8080:80"